#!/bin/env Rscript
# author: generated by Claude (Cowork) at user's request
# script: test-simulate.R
# desc: Standalone testthat tests for simulate.r (discrete-time transposon model)
# in:  Rscript test-simulate.R      (run from the SAME directory as simulate.r/func.r)
# out: console test report (testthat "summary" reporter)
# arg: NA
# date: 20260731
#
# NOTES FOR THE USER
# -------------------
# * simulate.r is a top-level SCRIPT driven by commandArgs(), not a set of
#   functions -- it cannot be "unit tested" in the usual sense without
#   amending it (which was explicitly ruled out). This file instead:
#     (1) runs simulate.r end-to-end, unchanged, as a subprocess against tiny
#         synthetic fixtures (a real integration/smoke test), and
#     (2) statically checks simulate.r's own source text for a couple of
#         specific, previously-identified inconsistencies that a smoke test
#         alone would not reliably surface.
#   Static/source-text checks are clearly labelled below.
# * Self-contained: builds its own tiny synthetic fixtures in a temp
#   directory mirroring the "code/ + ../raw/ + ../data/" layout both scripts
#   expect, and never touches your real ../raw or ../data folders.
# * This is the THIRD revision of this suite. This revision's simulate.r
#   reworks how a scenario is resolved: scenario.csv no longer carries any
#   rate/hypothesis columns itself -- it now has just two columns,
#   `transposon` and `host`, that PICK one transposon (by uniqID) out of
#   template-tpn.csv and one row (by position) out of the new template-
#   host.csv. Concretely:
#     tPn.0  = tPn.0[which(tPn.0$uniqID %in% sCene$transposon), ]   # by uniqID (value match)
#     host.0 = host.0[unique(sCene$host), ]                          # by row number (position match)
#   template-host.csv (recom, recomH1, cell, genotoxic) replaces the old
#   scenario.csv's cell/genotoxic/gene/recom columns; host.0$cell/$genotoxic/
#   $recom/$recomH1 are used everywhere those used to be sCene$cell/etc.
#   Fixture files below were rebuilt to this schema, confirmed directly
#   against the three uploaded CSVs (not inferred from code alone).
# * REGRESSION (this revision): the previous revision's fix for the
#   progress-print throttle -- changed from the tautological
#   `(gEn %% 1) == 0` to a genuine `(gEn %% 50) == 0` -- has been REVERTED.
#   This revision's simulate.r is back to `(gEn %% 1) == 0`. It is purely
#   cosmetic (console log verbosity only, no effect on simulation
#   correctness), but is flagged clearly below since it was previously
#   reported fixed and has now reappeared -- worth checking this wasn't an
#   accidental revert (e.g. an older snippet pasted back in) if that
#   throttle was intentionally wanted.
# * NEW FINDING (this revision): the host.0 selection line above
#   (`host.0[unique(sCene$host), ]`) selects by raw ROW POSITION, unlike the
#   transposon selection line right above it, which selects by uniqID VALUE
#   match. template-host.csv (unlike template-tpn.csv) carries no ID column
#   at all, so scenario.csv's "host" column IS a bare row number into it.
#   This is a fresh asymmetry introduced by this revision's host.0/template-
#   host.csv split (it did not exist before, since there was no host.0
#   previously) -- reordering, inserting, or deleting any row in template-
#   host.csv would silently repoint every scenario.csv "host" value at a
#   different row, with no error or ID check to catch it, whereas the
#   equivalent transposon mistake can't happen by construction. It may well
#   be an accepted convention given both catalogs look like static, append-
#   only outputs of a combinatorial generator (confirmed against the
#   uploaded template-tpn.csv/template-host.csv row counts and value
#   patterns) -- flagged as a consequence worth the user's awareness, not a
#   claim about intent.
# * IMPORTANT DISCLOSURE: authored and hand-traced line by line against
#   simulate.r's source (and the actual uploaded scenario.csv/template-
#   tpn.csv/template-host.csv, whose schemas were read directly), but could
#   NOT be executed in the authoring sandbox (no R interpreter available
#   there, no network access to install one). The `perturbGen` formula test
#   below WAS independently verified arithmetically (by hand-replicating R's
#   seq()/ceiling() semantics), not just re-derived from the source -- see
#   its comments for what that verification found. Please run this suite
#   yourself and treat the first run as a shakedown -- fix-forward on any
#   fixture mismatch rather than assuming the underlying analysis is wrong.

if (!requireNamespace("testthat", quietly = TRUE)) {
  stop("Package 'testthat' is required.\nInstall it with: install.packages('testthat')")
}
suppressPackageStartupMessages(library(testthat))

## ------------------------------------------------------------------------
## 0. Locate func.r and simulate.r without modifying them
## ------------------------------------------------------------------------
this_script_dir <- function() {
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", args, value = TRUE)
  if (length(file_arg) == 1) {
    return(dirname(normalizePath(sub("^--file=", "", file_arg[1]))))
  }
  getwd()
}

locate_file <- function(fname) {
  candidates <- unique(c(file.path(getwd(), fname), file.path(this_script_dir(), fname)))
  hit <- candidates[file.exists(candidates)]
  if (length(hit) == 0) {
    stop(sprintf(
      "Could not find '%s'.\nPlace test-simulate.R in the same directory as %s and run:\n  cd <that directory> && Rscript test-simulate.R",
      fname, fname
    ))
  }
  normalizePath(hit[1])
}

FUNC_R_PATH <- locate_file("func.r")
SIMULATE_R_PATH <- locate_file("simulate.r")
RSCRIPT_BIN <- file.path(R.home("bin"), "Rscript")

## ------------------------------------------------------------------------
## 1. Build an isolated temp project tree: code/ + raw/ + data/ (siblings),
##    exactly mirroring what func.r / simulate.r expect relative to CWD.
##    Kept deliberately tiny (population size 6, 2 generations) purely so
##    the end-to-end run finishes quickly.
## ------------------------------------------------------------------------
tmp_root <- file.path(tempdir(), paste0("simulate_r_tests_", as.integer(Sys.time())))
dir.create(file.path(tmp_root, "code"), recursive = TRUE)
dir.create(file.path(tmp_root, "raw"), recursive = TRUE)
dir.create(file.path(tmp_root, "data"), recursive = TRUE)

file.copy(FUNC_R_PATH, file.path(tmp_root, "code", "func.r"), overwrite = TRUE)
file.copy(SIMULATE_R_PATH, file.path(tmp_root, "code", "simulate.r"), overwrite = TRUE)

## -- template-tpn.csv: schema (11 columns) confirmed directly against the
##    uploaded file. Two distinct transposon "types" so scenario.csv's
##    uniqID-based selection is meaningfully exercised (not just trivially
##    the only row available).
writeLines(c(
  "gene,location,generation,valid,uniqID,size,jumpRate,jumpH1,copyRate,copyH1,copyDir",
  ",0,0,TRUE,TEST,50,0.1,fixed,0.1,fixed,both",
  ",0,0,TRUE,DEMO,50,0.05,evolving,0.05,charlesworth,terminus"
), file.path(tmp_root, "raw", "template-tpn.csv"))

## -- template-host.csv: schema (4 columns) confirmed directly against the
##    uploaded file. Two rows so scenario.csv's positional host selection is
##    meaningfully exercised (row 2, not just the default row 1). genotoxic
##    is kept at 0 for the row the smoke test actually selects, purely to
##    keep the end-to-end run fully deterministic (see the perturbGen
##    section below for why non-zero genotoxic interacts with small
##    generation counts in a way worth testing separately, not smoke-testing).
writeLines(c(
  "recom,recomH1,cell,genotoxic",
  "0.1,switch,haploid,1",
  "0.05,switch,haploid,0"
), file.path(tmp_root, "raw", "template-host.csv"))

gff_lines <- c(
  "seq1\ttest\tregion\t1\t2000\t.\t.\t.\tID=seq1",
  "seq1\ttest\tgene\t101\t400\t.\t+\t.\tID=gene-1;locus_tag=geneA;product=hypothetical protein A",
  "seq1\ttest\tgene\t451\t700\t.\t+\t.\tID=gene-2;locus_tag=geneB;product=hypothetical protein B",
  "seq1\ttest\tgene\t900\t1200\t.\t-\t.\tID=gene-3;locus_tag=geneC;product=recombinase-like protein",
  "seq1\ttest\tgene\t1500\t1900\t.\t-\t.\tID=gene-4;locus_tag=geneD;product=hypothetical protein D"
)
writeLines(gff_lines, file.path(tmp_root, "data", "genome.gff"))

## NOTE: "transposon size in bp" is dropped from this fixture -- as of this
## revision it is no longer read anywhere (transposon sizes come from
## template-tpn.csv's own `size` column instead).
input_csv <- c(
  "Type,Value",
  "ref genome,genome.fasta",
  "essential genes,geneA",
  "genes for recombination mechanism,geneC",
  "genes for fitness advantage,geneD",
  "transposon population size per genome distribution,poisson",
  "transposon population size per genome mean,2",
  "transposon population size per genome sd,2",
  "host organism constant population size,6",
  "host genome variation,6",
  "host genetic variation,2",
  "host organism constant generation number,2",
  "percentage transposon perturbation genotoxic,1",
  "percentage chance transposon perturbation boost,10",
  "percentage amplitude transposon perturbation boost,5",
  "percentage of fitness benefit with transposon,2"
)
writeLines(input_csv, file.path(tmp_root, "raw", "input.csv"))

## seed.csv: no header, one integer seed per row (argv[3] indexes into this)
writeLines(as.character(c(101, 202, 303)), file.path(tmp_root, "raw", "seed.csv"))

## scenario.csv: header=TRUE, schema (transposon,host) confirmed directly
## against the uploaded file. Row 1 picks transposon uniqID "DEMO" and host
## row 2 (recom=0.05, cell=haploid, genotoxic=0) -- row 2 specifically (not
## row 1) so the positional host lookup is genuinely exercised.
writeLines(c(
  "transposon,host",
  "DEMO,2"
), file.path(tmp_root, "raw", "scenario.csv"))

## ------------------------------------------------------------------------
## 2. Run simulate.r as a subprocess: real end-to-end smoke test, script
##    left completely unmodified.
## ------------------------------------------------------------------------
run_simulate <- function(seed_idx = "1", scenario_idx = "1") {
  old_wd <- getwd()
  on.exit(setwd(old_wd), add = TRUE)
  setwd(file.path(tmp_root, "code"))
  out <- suppressWarnings(system2(
    RSCRIPT_BIN,
    args = c("simulate.r", "../raw/input.csv", "../raw/seed.csv", seed_idx,
             "../raw/scenario.csv", scenario_idx),
    stdout = TRUE, stderr = TRUE
  ))
  status <- attr(out, "status")
  list(status = if (is.null(status)) 0L else status, output = out)
}

## ==========================================================================
## Run everything through testthat's summary reporter (see test-func.R for
## why with_reporter() is used: it lets a failing test report without
## aborting the rest of the suite).
## ==========================================================================
invisible(with_reporter("summary", start_end_reporter = TRUE, {

test_that("simulate.r runs end-to-end on tiny fixtures and writes a well-formed .rda", {
  res <- run_simulate(seed_idx = "1", scenario_idx = "1")
  if (!identical(res$status, 0L)) {
    cat("\n---- simulate.r stdout/stderr (see below for where it failed) ----\n")
    cat(paste(res$output, collapse = "\n"), "\n")
    cat("-------------------------------------------------------------------\n")
  }
  expect_equal(res$status, 0L)

  rda_path <- file.path(tmp_root, "data", "tPn--1_1.rda")
  expect_true(file.exists(rda_path))

  if (file.exists(rda_path)) {
    e <- new.env()
    load(rda_path, envir = e)
    expect_true(all(c("rec.host", "rec.transposon", "rec.offspring") %in% ls(e)))
    ## 2 generations requested -> rows 0..2 recorded -> 3 rows; 6 individuals -> 6 columns
    expect_equal(dim(e$rec.host), c(3, 6))
    expect_equal(dim(e$rec.transposon), c(3, 6))
    expect_equal(dim(e$rec.offspring), c(3, 6))
    ## every host should carry a ";"-joined pair of haplotype genome strings
    expect_true(all(grepl(";", as.matrix(e$rec.host)[1, ])))
  }
})

## ==========================================================================
## Static/source-text checks: simulate.r is not modularised, so these pin
## down specific, previously-identified inconsistencies directly against its
## source rather than through execution.
## ==========================================================================
simulate_src <- readLines(SIMULATE_R_PATH, warn = FALSE)
simulate_txt <- paste(simulate_src, collapse = "\n")

test_that("both the initial-population branch and the per-generation reproduction step read cell from host.0", {
  ## This revision moved `cell` from the old scenario.csv (sCene$cell) to
  ## the new template-host.csv (host.0$cell) at BOTH call sites: the initial
  ## population's haploid/diploid branch, and the main loop's
  ## host.reproduce() call. Checked directly against the source, and (since
  ## this is a rename rather than a fresh fix) confirming neither call site
  ## regressed back to a hardcoded "haploid" literal or the old sCene$cell.
  init_branch <- grep('host\\.0\\$cell\\s*==\\s*"haploid"', simulate_src, value = TRUE)
  expect_equal(length(init_branch), 1)

  reproduce_calls <- grep("host\\.reproduce\\(", simulate_src, value = TRUE)
  expect_equal(length(reproduce_calls), 1)  # exactly one call site in the main loop
  if (length(reproduce_calls) == 1) {
    expect_true(grepl('cell\\s*=\\s*host\\.0\\$cell', reproduce_calls))
    expect_false(grepl('cell\\s*=\\s*"haploid"', reproduce_calls))
    expect_false(grepl('cell\\s*=\\s*sCene\\$cell', reproduce_calls))
  }
})

test_that("[REGRESSION] the progress-print throttle has reverted to a tautology (gEn %% 1 again)", {
  ## Previously flagged as `(gEn %% 1) == 0` (always TRUE -- anything mod 1
  ## is 0, so this prints EVERY generation regardless of gEn), then fixed in
  ## an earlier revision to `(gEn %% 50) == 0` (a genuine throttle). This
  ## revision's simulate.r has REVERTED to `(gEn %% 1) == 0` -- the
  ## tautology is back. Purely cosmetic (console log verbosity only, no
  ## effect on simulation correctness), but flagged clearly since it was
  ## previously reported fixed. If unintentional, reinstating
  ## `(gEn %% 50) == 0` (or whatever interval is wanted) is the simplest fix.
  expect_false(grepl("gEn %% 1)", simulate_txt, fixed = TRUE))
  expect_true(grepl("gEn %% 50", simulate_txt, fixed = TRUE))
})

## NOTE: the sim.df0/sim.df1/sim.df2 dead per-generation debug snapshots
## remain commented out again this revision (`# sim.df0 = sim.df`, etc.)
## rather than live code, so that earlier-flagged concern stays resolved;
## the test that pinned it down stays removed.

test_that("[FINDING] transposon selection matches by uniqID value; host selection matches by row position", {
  ## simulate.r resolves a scenario row into working fixtures with two
  ## different lookup strategies:
  ##   tPn.0  = tPn.0[which(tPn.0$uniqID %in% sCene$transposon), ]  -- BY VALUE
  ##   host.0 = host.0[unique(sCene$host), ]                        -- BY POSITION
  ## template-host.csv has no id column of its own (confirmed against the
  ## uploaded file: recom,recomH1,cell,genotoxic only), so scenario.csv's
  ## "host" column can only ever be a bare row number. This is a new
  ## asymmetry introduced by this revision's host.0/template-host.csv split
  ## -- reordering template-host.csv would silently repoint scenario.csv's
  ## "host" values at different rows, with nothing to catch it, whereas the
  ## transposon side is immune to reordering by construction. Confirmed
  ## directly against the source below (a "finding"/awareness check, not a
  ## pass/fail bug assertion, since positional catalogs may be an accepted
  ## convention here).
  expect_true(any(grepl('tPn\\.0\\s*=\\s*tPn\\.0\\[which\\(tPn\\.0\\$uniqID %in% sCene\\$transposon\\)', simulate_src)))
  expect_true(any(grepl('host\\.0\\s*=\\s*host\\.0\\[unique\\(sCene\\$host\\)', simulate_src)))
})

test_that("perturbGen: genotoxic = N yields exactly N DISTINCT reachable perturbation generations (for a large enough gEn.max)", {
  ## simulate.r computes this inline (not as a function), so the formula is
  ## necessarily duplicated here rather than called directly -- if the
  ## formula in simulate.r ever changes, this copy must be updated too.
  ## NB: what actually matters behaviourally is DISTINCT generations, since
  ## simulate.r only ever checks membership (`gEn %in% perturbGen`) -- a
  ## repeated value in the vector doesn't create a second "hit". So this
  ## counts unique(reachable), not raw vector length.
  compute_perturbGen <- function(gEn.max, genotoxic) {
    perturbGen <- ceiling(rev(seq(1, gEn.max, gEn.max / (genotoxic + 1)))) - 1
    perturbGen[perturbGen == 0] <- gEn.max + 1
    perturbGen
  }
  ## Extended from a previous revision's {0,1,3} spot-check to the FULL
  ## genotoxic range actually present in the uploaded template-host.csv
  ## (confirmed: genotoxic takes every value 0-4 across its 100 rows).
  for (genotoxic in c(0, 1, 2, 3, 4)) {
    gEn.max <- 100
    pg <- compute_perturbGen(gEn.max, genotoxic)
    reachable <- unique(pg[pg <= gEn.max])
    expect_equal(length(reachable), genotoxic)
  }
})

test_that("[FINDING] perturbGen's 'exactly N reachable' property breaks down when gEn.max is small relative to genotoxic", {
  ## The formula is unchanged from the previous revision (only its source
  ## moved from sCene$genotoxic to host.0$genotoxic), but broadening the
  ## test above to genotoxic's full real-world range (0-4, per template-
  ## host.csv) surfaced something the old {0,1,3}-at-gEn.max=100 spot-check
  ## never exercised: ceiling()'s rounding can make two or more distinct raw
  ## perturbation points collapse onto the SAME integer generation when
  ## gEn.max is small relative to genotoxic+1, so the count of DISTINCT
  ## reachable perturbation generations ends up LESS than the nominal
  ## genotoxic value -- silently under-delivering the intended perturbation
  ## intensity for short runs, with no warning. Verified by hand (replicating
  ## R's seq()/ceiling() arithmetic, then de-duplicating since only distinct
  ## generations matter to `gEn %in% perturbGen`) for gEn.max = 2, matching
  ## this suite's own smoke-test generation count:
  ##   genotoxic=1 -> 1 distinct reachable (matches nominal, fine)
  ##   genotoxic=2 -> 1 distinct reachable (SHORT of nominal 2)
  ##   genotoxic=3 -> 1 distinct reachable (SHORT of nominal 3 -- collapses
  ##                  just as far as genotoxic=2 does, at this gEn.max)
  ##   genotoxic=4 -> 1 distinct reachable (SHORT of nominal 4, same reason)
  ## This is why the smoke test above deliberately selects a template-
  ## host.csv row with genotoxic=0 -- to stay fully deterministic rather
  ## than quietly depend on this edge case. Flagged as a fresh, previously
  ## untested consequence surfaced by knowing genotoxic's real range, not as
  ## a claim that the underlying formula itself changed this revision.
  compute_perturbGen <- function(gEn.max, genotoxic) {
    perturbGen <- ceiling(rev(seq(1, gEn.max, gEn.max / (genotoxic + 1)))) - 1
    perturbGen[perturbGen == 0] <- gEn.max + 1
    perturbGen
  }
  distinct_reachable <- function(gEn.max, genotoxic) {
    pg <- compute_perturbGen(gEn.max, genotoxic)
    length(unique(pg[pg <= gEn.max]))
  }
  gEn.max <- 2
  expect_equal(distinct_reachable(gEn.max, 1), 1)
  expect_equal(distinct_reachable(gEn.max, 2), 1)  # short of 2
  expect_equal(distinct_reachable(gEn.max, 3), 1)  # short of 3
  expect_equal(distinct_reachable(gEn.max, 4), 1)  # short of 4
})

}))  # end with_reporter()

## ==========================================================================
## Final note
## ==========================================================================
cat("\n==== test-simulate.R: NOTE ====\n",
    "All tests in this file are expected to PASS -- including the tests\n",
    "labelled [REGRESSION] and [FINDING], which document CURRENT behaviour\n",
    "rather than assert a pass/fail correctness bar. See the header comment\n",
    "block for the full write-up of what each one means. The end-to-end\n",
    "smoke test is the one most likely to need small fixture tweaks in a\n",
    "real environment (it exercises the full pipeline end to end).\n",
    "================================\n\n", sep = "")
