#!/bin/env Rscript
# author: generated by Claude (Cowork) at user's request
# script: test-simulate.R
# desc: Standalone testthat tests for simulate.r (discrete-time transposon model)
# in:  Rscript test-simulate.R      (run from the SAME directory as simulate.r/func.r)
# out: console test report (testthat "summary" reporter)
# arg: NA
# date: 20260730
#
# NOTES FOR THE USER
# -------------------
# * simulate.r is a top-level SCRIPT driven by commandArgs(), not a set of
#   functions -- it cannot be "unit tested" in the usual sense without
#   amending it (which was explicitly ruled out). This file instead:
#     (1) runs simulate.r end-to-end, unchanged, as a subprocess against tiny
#         synthetic fixtures (a real integration/smoke test), and
#     (2) statically checks simulate.r's own source text for a couple of
#         specific, previously-identified inconsistencies that a smoke test
#         alone would not reliably surface (e.g. a hardcoded argument that
#         only matters for certain scenario configurations).
#   Static/source-text checks are clearly labelled below; they are a
#   deliberate substitute for true unit tests given simulate.r's structure,
#   not an attempt to dress up something weaker as something it isn't.
# * Self-contained: builds its own tiny synthetic fixtures in a temp
#   directory mirroring the "code/ + ../raw/ + ../data/" layout both scripts
#   expect, and never touches your real ../raw or ../data folders.
# * This is the SECOND revision of this suite, updated against a corrected
#   simulate.r. The tests that previously pinned down the hardcoded
#   cell = "haploid" call and the always-true (gEn %% 1) == 0 throttle are
#   now rewritten to CONFIRM those fixes (see "## RESOLVED" comments); all
#   tests in this file are expected to pass.
# * IMPORTANT DISCLOSURE: authored and hand-traced line by line against
#   simulate.r's source, but could NOT be executed in the authoring sandbox
#   (no R interpreter available there, no network access to install one).
#   Please run this yourself and treat the first run as a shakedown --
#   fix-forward on any fixture mismatch rather than assuming the underlying
#   bug analysis is wrong. The end-to-end subprocess test in particular
#   exercises a lot of machinery at once and is the most likely to need a
#   tweak on first run in a real environment.

if (!requireNamespace("testthat", quietly = TRUE)) {
  stop("Package 'testthat' is required.\nInstall it with: install.packages('testthat')")
}
suppressPackageStartupMessages(library(testthat))

## ------------------------------------------------------------------------
## 0. Locate func.r and simulate.r without modifying them
## ------------------------------------------------------------------------
this_script_dir <- function() {
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", args, value = TRUE)
  if (length(file_arg) == 1) {
    return(dirname(normalizePath(sub("^--file=", "", file_arg[1]))))
  }
  getwd()
}

locate_file <- function(fname) {
  candidates <- unique(c(file.path(getwd(), fname), file.path(this_script_dir(), fname)))
  hit <- candidates[file.exists(candidates)]
  if (length(hit) == 0) {
    stop(sprintf(
      "Could not find '%s'.\nPlace test-simulate.R in the same directory as %s and run:\n  cd <that directory> && Rscript test-simulate.R",
      fname, fname
    ))
  }
  normalizePath(hit[1])
}

FUNC_R_PATH <- locate_file("func.r")
SIMULATE_R_PATH <- locate_file("simulate.r")
RSCRIPT_BIN <- file.path(R.home("bin"), "Rscript")

## ------------------------------------------------------------------------
## 1. Build an isolated temp project tree: code/ + raw/ + data/ (siblings),
##    exactly mirroring what func.r / simulate.r expect relative to CWD.
##    Kept deliberately tiny (population size 6, 2 generations) purely so
##    the end-to-end run finishes quickly.
## ------------------------------------------------------------------------
tmp_root <- file.path(tempdir(), paste0("simulate_r_tests_", as.integer(Sys.time())))
dir.create(file.path(tmp_root, "code"), recursive = TRUE)
dir.create(file.path(tmp_root, "raw"), recursive = TRUE)
dir.create(file.path(tmp_root, "data"), recursive = TRUE)

file.copy(FUNC_R_PATH, file.path(tmp_root, "code", "func.r"), overwrite = TRUE)
file.copy(SIMULATE_R_PATH, file.path(tmp_root, "code", "simulate.r"), overwrite = TRUE)

writeLines(c(
  "gene,loc,gen,valid,uniqID,size,jump,copy",
  "gPLACEHOLDER,0,0,TRUE,AAAAAAA,1,0.01,0.01"
), file.path(tmp_root, "raw", "tpn-template.csv"))

gff_lines <- c(
  "seq1\ttest\tregion\t1\t2000\t.\t.\t.\tID=seq1",
  "seq1\ttest\tgene\t101\t400\t.\t+\t.\tID=gene-1;locus_tag=geneA;product=hypothetical protein A",
  "seq1\ttest\tgene\t451\t700\t.\t+\t.\tID=gene-2;locus_tag=geneB;product=hypothetical protein B",
  "seq1\ttest\tgene\t900\t1200\t.\t-\t.\tID=gene-3;locus_tag=geneC;product=recombinase-like protein",
  "seq1\ttest\tgene\t1500\t1900\t.\t-\t.\tID=gene-4;locus_tag=geneD;product=hypothetical protein D"
)
writeLines(gff_lines, file.path(tmp_root, "data", "genome.gff"))

## NOTE: reGeneDF()'s old NA-propagation risk with multiple ';'-separated
## transposon sizes is now fixed (it reads each transposon's own size field
## directly -- see test-func.R), so that is no longer a reason to avoid
## multiple sizes here. "transposon size in bp" is still kept as a single
## value for this smoke test simply to keep it focused on general plumbing;
## "host organism constant population size" and "...generation number" are
## kept tiny purely for run time.
input_csv <- c(
  "Type,Value",
  "ref genome,genome.fasta",
  "essential genes,geneA",
  "genes for recombination mechanism,geneC",
  "genes for fitness advantage,geneD",
  "transposon population size per genome distribution,poisson",
  "transposon population size per genome mean,2",
  "transposon population size per genome sd,2",
  "host organism constant population size,6",
  "host genome variation,6",
  "host genetic variation,2",
  "transposon size in bp,50",
  "host organism constant generation number,2",
  "percentage transposon perturbation genotoxic,1",
  "percentage chance transposon perturbation boost,10",
  "percentage amplitude transposon perturbation boost,5",
  "percentage of fitness benefit with transposon,2"
)
writeLines(input_csv, file.path(tmp_root, "raw", "input.csv"))

## seed.csv: no header, one integer seed per row (argv[3] indexes into this)
writeLines(as.character(c(101, 202, 303)), file.path(tmp_root, "raw", "seed.csv"))

## scenario.csv: header=TRUE; column order inferred from func.r/simulate.r
## usage -- see test-func.R for the detailed reasoning (sCene[2]/sCene[4]
## read positionally as hypothesis-name strings inside sCene.mod()).
writeLines(c(
  "jumpRate,jumpHypothesis,copyRate,copyHypothesis,genotoxic,cell,gene,recom,copyDir",
  "0.05,fixed rate,0.02,fixed rate,1,haploid,0.05,switch,terminus"
), file.path(tmp_root, "raw", "scenario.csv"))

## ------------------------------------------------------------------------
## 2. Run simulate.r as a subprocess: real end-to-end smoke test, script
##    left completely unmodified.
## ------------------------------------------------------------------------
run_simulate <- function(seed_idx = "1", scenario_idx = "1") {
  old_wd <- getwd()
  on.exit(setwd(old_wd), add = TRUE)
  setwd(file.path(tmp_root, "code"))
  out <- suppressWarnings(system2(
    RSCRIPT_BIN,
    args = c("simulate.r", "../raw/input.csv", "../raw/seed.csv", seed_idx,
             "../raw/scenario.csv", scenario_idx),
    stdout = TRUE, stderr = TRUE
  ))
  status <- attr(out, "status")
  list(status = if (is.null(status)) 0L else status, output = out)
}

## ==========================================================================
## Run everything through testthat's summary reporter (see test-func.R for
## why with_reporter() is used: it lets a failing test report without
## aborting the rest of the suite -- relevant if a future regression
## reintroduces one of the issues confirmed fixed below).
## ==========================================================================
invisible(with_reporter("summary", start_end_reporter = TRUE, {

test_that("simulate.r runs end-to-end on tiny fixtures and writes a well-formed .rda", {
  skip_on_cran <- TRUE  # not a CRAN package; kept for clarity only, not used
  res <- run_simulate(seed_idx = "1", scenario_idx = "1")
  if (!identical(res$status, 0L)) {
    cat("\n---- simulate.r stdout/stderr (see below for where it failed) ----\n")
    cat(paste(res$output, collapse = "\n"), "\n")
    cat("-------------------------------------------------------------------\n")
  }
  expect_equal(res$status, 0L)

  rda_path <- file.path(tmp_root, "data", "tPn--1_1.rda")
  expect_true(file.exists(rda_path))

  if (file.exists(rda_path)) {
    e <- new.env()
    load(rda_path, envir = e)
    expect_true(all(c("rec.host", "rec.transposon", "rec.offspring") %in% ls(e)))
    ## 2 generations requested -> rows 0..2 recorded -> 3 rows; 6 individuals -> 6 columns
    expect_equal(dim(e$rec.host), c(3, 6))
    expect_equal(dim(e$rec.transposon), c(3, 6))
    expect_equal(dim(e$rec.offspring), c(3, 6))
    ## every host should carry a ";"-joined pair of haplotype genome strings
    expect_true(all(grepl(";", as.matrix(e$rec.host)[1, ])))
  }
})

## ==========================================================================
## Static/source-text checks: simulate.r is not modularised, so these pin
## down specific, previously-identified inconsistencies directly against its
## source rather than through execution. See the accompanying chat summary
## for full write-ups; comments here are intentionally brief pointers back
## to it.
## ==========================================================================
simulate_src <- readLines(SIMULATE_R_PATH, warn = FALSE)
simulate_txt <- paste(simulate_src, collapse = "\n")

test_that("the per-generation reproduction step now passes cell = sCene$cell through correctly", {
  ## RESOLVED: the main loop's host.reproduce() call now passes
  ## cell = sCene$cell instead of a hardcoded "haploid" literal, matching
  ## the initial population setup a few lines above (which already branched
  ## on sCene$cell). Checked directly against the source:
  reproduce_calls <- grep("host\\.reproduce\\(", simulate_src, value = TRUE)
  expect_equal(length(reproduce_calls), 1)  # exactly one call site in the main loop
  if (length(reproduce_calls) == 1) {
    expect_true(grepl('cell\\s*=\\s*sCene\\$cell', reproduce_calls))
    expect_false(grepl('cell\\s*=\\s*"haploid"', reproduce_calls))
  }
})

test_that("the progress-print throttle is no longer a tautology", {
  ## RESOLVED: the condition changed from `(gEn %% 1) == 0` (anything mod 1
  ## is 0, so this printed EVERY generation regardless of gEn) to
  ## `(gEn %% 50) == 0`, which genuinely throttles the message to roughly
  ## every 50th generation.
  expect_true(grepl("gEn %% 50", simulate_txt, fixed = TRUE))
  expect_false(grepl("gEn %% 1)", simulate_txt, fixed = TRUE))
  sometimes_false <- any(sapply(1:49, function(g) (g %% 50) != 0))
  expect_true(sometimes_false)
})

## NOTE: the previous revision flagged sim.df0/sim.df1/sim.df2 as dead
## per-generation debug snapshots (assigned, never read back). They are now
## commented out (`# sim.df0 = sim.df`, etc.) rather than live code, so the
## concern is resolved and the test that pinned it down has been removed.

test_that("perturbGen: genotoxic = N yields exactly N reachable perturbation generations", {
  ## simulate.r computes this inline (not as a function), so the formula is
  ## necessarily duplicated here rather than called directly -- if the
  ## formula in simulate.r ever changes, this copy must be updated too.
  compute_perturbGen <- function(gEn.max, genotoxic) {
    perturbGen <- ceiling(rev(seq(1, gEn.max, gEn.max / (genotoxic + 1)))) - 1
    perturbGen[perturbGen == 0] <- gEn.max + 1
    perturbGen
  }
  for (genotoxic in c(0, 1, 3)) {
    gEn.max <- 100
    pg <- compute_perturbGen(gEn.max, genotoxic)
    reachable <- pg[pg <= gEn.max]
    expect_equal(length(reachable), genotoxic)
  }
})

}))  # end with_reporter()

## ==========================================================================
## Final note
## ==========================================================================
cat("\n==== test-simulate.R: NOTE ====\n",
    "All tests in this file are expected to PASS against the current\n",
    "simulate.r. The end-to-end smoke test is the one most likely to need\n",
    "small fixture tweaks in a real environment (it exercises the full\n",
    "pipeline end to end).\n",
    "================================\n\n", sep = "")
