#!/bin/env Rscript
# author: generated by Claude (Cowork) at user's request
# script: test-func.R
# desc: Standalone testthat unit tests for func.r (transposon ecology simulation helpers)
# in:  Rscript test-func.R      (run from the SAME directory as func.r)
# out: console test report (testthat "summary" reporter)
# arg: NA
# date: 20260730
#
# NOTES FOR THE USER
# -------------------
# * This script is self-contained: it builds its own tiny synthetic fixtures
#   (a fake GFF, input.csv, tpn-template.csv) inside a temp directory that
#   mirrors the "code/ + ../raw/ + ../data/" layout func.r expects, so it
#   never touches your real ../raw or ../data folders.
# * func.r is sourced UNCHANGED (no amendments) from wherever this script
#   finds it (same directory as this script, or current working directory).
# * This is the THIRD revision of this suite, updated against a corrected
#   func.r each time. Per the user's instructions: tests for issues that
#   were fixed were rewritten to confirm the fix (see "## RESOLVED"
#   comments); tests for issues left unchanged were REMOVED rather than kept
#   as expected failures (see "## NOTE: ... unchanged ... deliberately"
#   comments marking where each used to be). All tests in this file are now
#   expected to PASS -- the rNumVec "uniform" min>max case flagged in the
#   previous revision is fixed as of this one too.
# * IMPORTANT DISCLOSURE: this script was authored and hand-traced line by
#   line against func.r's source, but could NOT be executed in the authoring
#   sandbox (no R interpreter available there, and no network access to
#   install one). Please run it yourself with `Rscript test-func.R` and treat
#   the first run as a shakedown -- open an issue/fix-forward on any fixture
#   mismatch rather than assuming the underlying bug analysis is wrong.

if (!requireNamespace("testthat", quietly = TRUE)) {
  stop("Package 'testthat' is required.\nInstall it with: install.packages('testthat')")
}
suppressPackageStartupMessages(library(testthat))

## ------------------------------------------------------------------------
## 0. Locate func.r without modifying it
## ------------------------------------------------------------------------
this_script_dir <- function() {
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", args, value = TRUE)
  if (length(file_arg) == 1) {
    return(dirname(normalizePath(sub("^--file=", "", file_arg[1]))))
  }
  getwd()
}

locate_file <- function(fname) {
  candidates <- unique(c(file.path(getwd(), fname), file.path(this_script_dir(), fname)))
  hit <- candidates[file.exists(candidates)]
  if (length(hit) == 0) {
    stop(sprintf(
      "Could not find '%s'.\nPlace test-func.R in the same directory as %s and run:\n  cd <that directory> && Rscript test-func.R",
      fname, fname
    ))
  }
  normalizePath(hit[1])
}

FUNC_R_PATH <- locate_file("func.r")

## ------------------------------------------------------------------------
## 1. Build an isolated temp project tree: code/ + raw/ + data/ (siblings)
##    func.r's top-level `read.csv("../raw/tpn-template.csv")` and
##    inParams()'s internal "../raw/..." / "../data/..." reads are resolved
##    relative to the working directory, so we build exactly the layout it
##    expects and never touch the user's real raw/ or data/ folders.
## ------------------------------------------------------------------------
tmp_root <- file.path(tempdir(), paste0("func_r_tests_", as.integer(Sys.time())))
dir.create(file.path(tmp_root, "code"), recursive = TRUE)
dir.create(file.path(tmp_root, "raw"), recursive = TRUE)
dir.create(file.path(tmp_root, "data"), recursive = TRUE)

file.copy(FUNC_R_PATH, file.path(tmp_root, "code", "func.r"), overwrite = TRUE)

## -- tpn-template.csv: only the 8 column NAMES / ncol() are ever used by
##    func.r (ini.transposon uses ncol(template); tPn.io uses colnames(ref)
##    and ncol(ref)) -- the data row's actual values are never read.
writeLines(c(
  "gene,loc,gen,valid,uniqID,size,jump,copy",
  "gPLACEHOLDER,0,0,TRUE,AAAAAAA,1,0.01,0.01"
), file.path(tmp_root, "raw", "tpn-template.csv"))

## -- a minimal but structurally realistic GFF3 body (tab-separated, 9 cols,
##    no header) with one "region" row (whole-sequence length) and 4 gene
##    rows carrying locus_tag + product attributes.
gff_lines <- c(
  "seq1\ttest\tregion\t1\t2000\t.\t.\t.\tID=seq1",
  "seq1\ttest\tgene\t101\t400\t.\t+\t.\tID=gene-1;locus_tag=geneA;product=hypothetical protein A",
  "seq1\ttest\tgene\t451\t700\t.\t+\t.\tID=gene-2;locus_tag=geneB;product=hypothetical protein B",
  "seq1\ttest\tgene\t900\t1200\t.\t-\t.\tID=gene-3;locus_tag=geneC;product=recombinase-like protein",
  "seq1\ttest\tgene\t1500\t1900\t.\t-\t.\tID=gene-4;locus_tag=geneD;product=hypothetical protein D"
)
writeLines(gff_lines, file.path(tmp_root, "data", "genome.gff"))

## -- input.csv: Type/Value pairs consumed by inParams()
input_csv <- c(
  "Type,Value",
  "ref genome,genome.fasta",
  "essential genes,geneA",
  "genes for recombination mechanism,geneC",
  "genes for fitness advantage,geneD",
  "transposon population size per genome distribution,poisson",
  "transposon population size per genome mean,3",
  "transposon population size per genome sd,3",
  "host organism constant population size,6",
  "host genome variation,6",
  "host genetic variation,2",
  "transposon size in bp,50",
  "host organism constant generation number,3",
  "percentage transposon perturbation genotoxic,10",
  "percentage chance transposon perturbation boost,10",
  "percentage amplitude transposon perturbation boost,5",
  "percentage of fitness benefit with transposon,2"
)
writeLines(input_csv, file.path(tmp_root, "raw", "input.csv"))

## -- a one-row scenario fixture, shared by tests that need `scenario`/`sCene`
##    Column order inferred from func.r usage: sCene[2] & sCene[4] are read
##    POSITIONALLY as hypothesis-name strings inside sCene.mod(), while
##    jumpRate/copyRate/genotoxic/cell/gene/recom/copyDir are read BY NAME.
scenario_fixture <- data.frame(
  jumpRate = 0.05, jumpHypothesis = "fixed rate",
  copyRate = 0.02, copyHypothesis = "fixed rate",
  genotoxic = 1, cell = "haploid", gene = 0.01,
  recom = "switch", copyDir = "terminus",
  stringsAsFactors = FALSE
)

## ------------------------------------------------------------------------
## 2. Source func.r with the working directory pointed at code/, as func.r
##    itself assumes (it is written to be `source()`d from its own folder).
## ------------------------------------------------------------------------
old_wd <- getwd()
setwd(file.path(tmp_root, "code"))
source("func.r", chdir = FALSE)  # tPn.0 <- read.csv("../raw/tpn-template.csv") runs here
on.exit(setwd(old_wd), add = TRUE)

## ------------------------------------------------------------------------
## 3. Small shared helpers for building fixtures by hand
## ------------------------------------------------------------------------

## Build one flat "!"-joined transposon record matching tPn.0's 8 columns
mk_tpn <- function(gene, loc, gen, valid = TRUE, uniqID = "AAAAAAA",
                    size = 50, jump = 0.05, copy = 0.02) {
  paste(c(gene, loc, gen, valid, uniqID, size, jump, copy), collapse = "!")
}

## Build a small, hand-controlled gene.df with the exact columns inParams()
## produces (locus_tag, start, end, product, length, interLength, essential,
## recombination, advantage), WITHOUT the haplotype doubling, for tests that
## need precise, deterministic control over gene boundaries.
mk_gene_df <- function(locus_tag, start, end, product = "x",
                        essential = FALSE, recombination = FALSE, advantage = FALSE) {
  n <- length(locus_tag)
  df <- data.frame(
    locus_tag = locus_tag, start = start, end = end, product = product,
    stringsAsFactors = FALSE
  )
  df$length <- df$end - df$start + 1
  df$interLength <- c(df$start[1] - 1, df$start[-1] - df$end[-n])
  df$essential <- rep_len(essential, n)
  df$recombination <- rep_len(recombination, n)
  df$advantage <- rep_len(advantage, n)
  df
}

## A realistic, fully-doubled gene.df + params, obtained by actually running
## inParams() against the synthetic fixtures above (this exercises inParams()
## itself, and gives every other test a schema-correct fixture to build on).
in_file <- inParams("../raw/input.csv")

## ------------------------------------------------------------------------
## 4. All test_that() blocks run inside with_reporter() so that a failing
##    test is recorded and printed, but does NOT abort the rest of the suite
##    (this is the same mechanism test_dir()/test_file() use internally;
##    without it, a bare top-level test_that() failure can halt a plain
##    script). All tests here are currently expected to pass, but this
##    protects against a future regression hiding later failures.
## ------------------------------------------------------------------------
invisible(with_reporter("summary", start_end_reporter = TRUE, {

## ==========================================================================
## gffClean()
## ==========================================================================
test_that("gffClean assigns the 9 standard GFF columns and expands attributes", {
  raw <- read.table(file.path(tmp_root, "data", "genome.gff"),
                     sep = "\t", header = FALSE, quote = "")
  cleaned <- gffClean(raw)
  expect_true(all(c("locus_tag", "product") %in% colnames(cleaned)))
  expect_equal(nrow(cleaned), nrow(raw))
  expect_equal(cleaned$locus_tag[cleaned$type == "gene"], c("geneA", "geneB", "geneC", "geneD"))
  expect_equal(cleaned$product[cleaned$type == "region"], NA_character_)
})

test_that("gffClean fills a data.frame position with NA when a row's tag is unseen elsewhere", {
  ## sanity check on the cbind/aTt matrix construction: a row with a tag no
  ## other row has should still produce a well-formed data.frame column
  raw <- read.table(text = paste(
    "s1\ta\tregion\t1\t100\t.\t.\t.\tID=s1",
    "s1\ta\tgene\t1\t10\t.\t+\t.\tID=g1;locus_tag=g1;product=p;onlyhere=zz",
    sep = "\n"
  ), sep = "\t", header = FALSE, quote = "")
  cleaned <- gffClean(raw)
  expect_true("onlyhere" %in% colnames(cleaned))
  expect_true(is.na(cleaned$onlyhere[cleaned$type == "region"]))
})

## NOTE: gffClean() is unchanged from the version originally reviewed, so per
## the user's instruction its previously-flagged "=" -splitting fragility
## (an attribute VALUE containing "=" gets truncated, and can add a spurious
## extra column) is being left as-is deliberately, and the test that pinned
## it down has been removed rather than kept as an expected failure.

## ==========================================================================
## rNumVec()
## ==========================================================================
test_that("rNumVec normal/uniform/poisson/negbin all return length L", {
  set.seed(1)
  expect_length(rNumVec("normal", L = 5, p1 = 10, p2 = 1), 5)
  expect_length(rNumVec("uniform", L = 5, p1 = 10, p2 = 1), 5)
  expect_length(rNumVec("poisson", L = 5, p1 = 3), 5)
  expect_length(rNumVec("negbin", L = 5, p1 = 0.5, p2 = 3), 5)
})

test_that("rNumVec poisson/negbin outputs are always in (0, 1]", {
  set.seed(2)
  x <- rNumVec("poisson", L = 200, p1 = 4)
  expect_true(all(x > 0 & x <= 1))
  y <- rNumVec("negbin", L = 200, p1 = 0.3, p2 = 4)
  expect_true(all(y > 0 & y <= 1))
})

test_that("rNumVec rejects unsupported distribution names", {
  expect_error(rNumVec("gamma", L = 1, p1 = 1, p2 = 1))
})

test_that("rNumVec uniform: the original asymmetric-skew case (p1 < p2) is fixed", {
  ## RESOLVED: max is now ALSO clamped, to min(1, p1+p2), alongside
  ## min = max(0, p1-p2). For p1=1, p2=5 this makes the draw a plain
  ## Uniform(0,1) instead of the old Uniform(0,6) (whose mean sat well above
  ## p1). Re-checked for this exact case, which previously failed.
  set.seed(3)
  p1 <- 1; p2 <- 5
  draws <- rNumVec("uniform", L = 100000, p1 = p1, p2 = p2)
  expect_true(all(draws >= 0 & draws <= 1))
  expect_equal(mean(draws), 0.5, tolerance = 0.02)
})

test_that("rNumVec uniform: min can no longer end up above max", {
  ## RESOLVED: min is now max(0, min(1, p1-p2)) -- an ADDITIONAL inner
  ## min(1, ...) clamp -- alongside max = min(1, p1+p2). This guarantees
  ## min <= max for any non-negative p1, p2, closing the min > max case
  ## previously demonstrated for p1=5, p2=1 (min=4, max=1 under the prior
  ## revision of this fix). Re-checked for that exact case, which
  ## previously failed:
  p1 <- 5; p2 <- 1
  min_val <- max(0, min(1, p1 - p2))
  max_val <- min(1, p1 + p2)
  expect_true(min_val <= max_val)  # confirms the ordering now holds (1 <= 1)

  set.seed(14)
  draws <- rNumVec("uniform", L = 10000, p1 = p1, p2 = p2)
  expect_true(all(draws >= 0 & draws <= 1))
  ## NOTE (not a bug, just worth knowing): with p1 - p2 (=4) > 1, both bounds
  ## now collapse to exactly 1, so runif(min=1, max=1) deterministically
  ## returns 1 every time -- a single point, not a spread, for this
  ## parameter combination. Still well-defined and no longer "broken".
  expect_equal(draws, rep(1, 10000))
})

## ==========================================================================
## inParams()
## ==========================================================================
test_that("inParams returns params/gene/transposon.titre/genome with expected shapes", {
  expect_true(all(c("params", "gene", "transposon.titre", "genome") %in% names(in_file)))
  ## 4 genes in the GFF, doubled for the two haplotype copies
  expect_equal(nrow(in_file$gene), 8)
  expect_true(all(c(0, 1) == unique(substr(in_file$gene$locus_tag, 1, 1))))
  ## population-size titres: one non-negative integer-ish count per individual
  expect_equal(length(in_file$transposon.titre), 6)
  expect_true(all(in_file$transposon.titre >= 1))
})

test_that("inParams correctly flags essential / recombination / advantage genes on both haplotypes", {
  expect_true(all(in_file$gene$essential[in_file$gene$locus_tag %in% c("0geneA", "1geneA")]))
  expect_true(all(in_file$gene$recombination[in_file$gene$locus_tag %in% c("0geneC", "1geneC")]))
  expect_true(all(in_file$gene$advantage[in_file$gene$locus_tag %in% c("0geneD", "1geneD")]))
  expect_false(any(in_file$gene$essential[in_file$gene$locus_tag %in% c("0geneB", "1geneB")]))
})

test_that("inParams intergenic lengths are non-negative and consistent with gene coordinates", {
  one_copy <- in_file$gene[substr(in_file$gene$locus_tag, 1, 1) == "0", ]
  expect_true(all(one_copy$interLength >= 0))
  expect_equal(sum(one_copy$length, one_copy$interLength), in_file$genome / 2)
})

## NOTE: inParams() is unchanged, so its previously-flagged circular
## wrap-around issue (`gEne$length[x-1] <- ...` silently no-ops when the
## negative gap is at row 1, since `x-1 == 0`) is being left as-is
## deliberately; the test that pinned it down has been removed.

## ==========================================================================
## ini.host()
## ==========================================================================
test_that("ini.host returns one genome string per host, length = number of genes", {
  set.seed(4)
  hosts <- ini.host(host.var = 10, gene.df = in_file$gene, gene.var = 2)
  expect_length(hosts, 10)
  expect_true(all(nchar(hosts) == nrow(in_file$gene) / 2))
})

test_that("ini.host recycles a single variation value across all genes", {
  set.seed(5)
  hosts <- ini.host(host.var = 20, gene.df = in_file$gene, gene.var = "2")
  alleles <- toupper(unlist(strsplit(hosts, "")))
  expect_true(all(alleles %in% c("A", "B")))
})

test_that("ini.host errors when too few per-gene variation values are supplied", {
  nGene <- nrow(in_file$gene) / 2
  expect_error(ini.host(host.var = 5, gene.df = in_file$gene,
                         gene.var = paste(rep(2, nGene - 1), collapse = ";")))
})

test_that("ini.host warns and truncates when too many per-gene variation values are supplied", {
  nGene <- nrow(in_file$gene) / 2
  expect_warning(ini.host(host.var = 5, gene.df = in_file$gene,
                           gene.var = paste(rep(2, nGene + 2), collapse = ";")))
})

test_that("ini.host clamps (and warns on) a variation count above 26, instead of yielding NA alleles", {
  ## RESOLVED: ini.host now explicitly checks `gene.var > length(LETTERS)`,
  ## clamps it to 26, and warns -- rather than silently indexing LETTERS out
  ## of bounds (which used to yield NA alleles).
  set.seed(6)
  expect_warning(
    hosts <- ini.host(host.var = 5, gene.df = in_file$gene[1:2, ], gene.var = 27),
    "Too many alleles"
  )
  expect_false(any(is.na(hosts)))
})

test_that("ini.host clamps (and warns on) a variation count below 1, instead of relying on R's 1:0 idiom", {
  ## RESOLVED: ini.host now explicitly checks `gene.var < 1`, clamps it to 1,
  ## and warns -- rather than silently falling through R's `1:0 == c(1,0)`
  ## idiom with no feedback that the input was invalid.
  expect_warning(
    hosts <- ini.host(host.var = 5, gene.df = in_file$gene[1:2, ], gene.var = 0),
    "Too few alleles"
  )
  expect_false(any(is.na(hosts)))
  expect_true(all(toupper(hosts) == "A"))  # clamped to exactly 1 allele -> always "A"/"a"
})

## ==========================================================================
## ini.transposon()
## ==========================================================================
test_that("ini.transposon builds one row per requested transposon with matching size", {
  set.seed(7)
  tp <- ini.transposon(tPn.size = "50;80;120", scenario = scenario_fixture)
  expect_equal(nrow(tp), 3)
  expect_equal(tp$size, c(50, 80, 120))
  expect_equal(nchar(tp$uniqID), rep(7, 3))
  parsed <- tPn.io(tp$ini[1])
  expect_equal(as.numeric(parsed["jump"]), scenario_fixture$jumpRate)
  expect_equal(as.numeric(parsed["copy"]), scenario_fixture$copyRate)
  expect_true(as.logical(parsed["valid"]))
})

test_that("ini.transposon accepts a single scalar size (no ';')", {
  set.seed(8)
  tp <- ini.transposon(tPn.size = "60", scenario = scenario_fixture)
  expect_equal(nrow(tp), 1)
  expect_equal(tp$size, 60)
})

## ==========================================================================
## reZero()
## ==========================================================================
test_that("reZero linearly rescales x from [new0, new1] to [0, 1]", {
  expect_equal(reZero(5, new0 = 0, new1 = 10), 0.5)
  expect_equal(reZero(0, new0 = -5, new1 = 5), 0.5)
  expect_equal(reZero(10, new0 = 0, new1 = 10), 1)
})

## ==========================================================================
## tPn.io()
## ==========================================================================
test_that("tPn.io round-trips a single transposon: vector -> string -> named vector", {
  flat <- mk_tpn("gGENE1", 10, 0, size = 55)
  parsed <- tPn.io(flat)
  expect_equal(names(parsed), colnames(tPn.0))
  expect_equal(parsed[["gene"]], "gGENE1")
  expect_equal(as.numeric(parsed[["size"]]), 55)
})

test_that("tPn.io round-trips multiple ';'-joined transposons into a data.frame", {
  flat <- paste(mk_tpn("gGENE1", 1, 0), mk_tpn("iGENE2", 2, 0), sep = ";")
  parsed <- tPn.io(flat)
  expect_s3_class(parsed, "data.frame")
  expect_equal(nrow(parsed), 2)
  expect_equal(colnames(parsed), colnames(tPn.0))
})

test_that("tPn.io converts a data.frame of transposons back into a ';'-joined string", {
  df <- data.frame(gene = c("gA", "iB"), loc = c(1, 2), gen = c(0, 0),
                    valid = c(TRUE, TRUE), uniqID = c("AAAAAAA", "BBBBBBB"),
                    size = c(50, 60), jump = c(0.1, 0.1), copy = c(0.1, 0.1))
  s <- tPn.io(df)
  expect_equal(s, paste(mk_tpn("gA", 1, 0, size = 50, jump = 0.1, copy = 0.1),
                         mk_tpn("iB", 2, 0, size = 60, jump = 0.1, copy = 0.1), sep = ";"))
})

test_that("tPn.io errors when given the wrong number of loose values", {
  expect_error(tPn.io(c("only", "two")))
})

## ==========================================================================
## reGeneDF()
## ==========================================================================
test_that("reGeneDF grows a gene's length in place for a coding-region ('g') insertion", {
  gdf <- mk_gene_df(c("g1", "g2"), start = c(1, 50), end = c(40, 90))
  tpn <- mk_tpn(paste0("g", "g1"), 5, 0, size = 20)
  out <- reGeneDF(tpn, gene.df = gdf)
  expect_equal(out$length[1], 40 - 1 + 1 + 20)
  expect_equal(out$start[2], 50 + 20)
  expect_equal(out$end[2], 90 + 20)
})

test_that("reGeneDF grows the intergenic gap for an intergenic ('i') insertion", {
  gdf <- mk_gene_df(c("g1", "g2"), start = c(1, 50), end = c(40, 90))
  tpn <- mk_tpn(paste0("i", "g2"), 5, 0, size = 15)
  out <- reGeneDF(tpn, gene.df = gdf)
  expect_equal(out$interLength[2], gdf$interLength[2] + 15)
  expect_equal(out$start[2], 50 + 15)
})

test_that("reGeneDF now reads each transposon's own recorded size instead of an external constant", {
  ## RESOLVED: reGeneDF() dropped its `tPn.size` parameter entirely and now
  ## computes as.numeric(i0[6]) -- the transposon's own `size` field --
  ## matching how tPn.reloc() already worked. Confirmed here with two
  ## differently-sized transposons applied to the same gene table: each
  ## should grow it by ITS OWN size, not a shared/external value. This also
  ## removes the old NA-propagation risk from simulate.r passing a
  ## ';'-separated multi-size string through as.numeric().
  gdf <- mk_gene_df(c("g1", "g2"), start = c(1, 50), end = c(40, 90))

  tpn_small <- mk_tpn("gg1", 5, 0, size = 20)
  out_small <- reGeneDF(tpn_small, gene.df = gdf)
  expect_equal(out_small$length[1], 40 - 1 + 1 + 20)

  tpn_large <- mk_tpn("gg1", 5, 0, size = 999)
  out_large <- reGeneDF(tpn_large, gene.df = gdf)
  expect_equal(out_large$length[1], 40 - 1 + 1 + 999)
})

## ==========================================================================
## host.reproduce()
## ==========================================================================
test_that("host.reproduce returns one offspring row per parent for haploid reproduction", {
  ## host.reproduce() expects each pool$host entry to be TWO ";"-joined
  ## haplotype-copy strings (per haploid-model convention -- see simulate.r's
  ## `paste(hOst[fTree[,1]], hOst[fTree[,2]], sep=";")`), each nGene chars long.
  set.seed(9)
  pool <- data.frame(
    host = c("AaBb;AaBb", "aabb;aabb", "AABB;AABB"),
    transposon = c("", "", ""),
    familyTree = c("1;1", "2;2", "3;3"),
    stringsAsFactors = FALSE
  )
  off <- host.reproduce(pool, gene.df = in_file$gene, fitness.advantage = 2, cell = "haploid")
  expect_equal(nrow(off), nrow(pool))
  expect_true(all(grepl(";", off$host)))
})

test_that("host.reproduce penalises offspring probability when an essential gene is disrupted", {
  ess_tag <- in_file$gene$locus_tag[in_file$gene$essential][1]  # e.g. "0geneA"
  pool <- data.frame(
    host = c("AAAA;AAAA", "AAAA;AAAA"),
    transposon = c("", mk_tpn(paste0("g", ess_tag), 1, 0)),
    familyTree = c("1;1", "2;2"),
    stringsAsFactors = FALSE
  )
  ## host 2 disrupts an essential gene on one haplotype copy only, so it is
  ## disadvantaged but not fully excluded -- resample with distinct seeds
  ## and check it is chosen as a parent less than half the time on average
  ## (the null/no-effect expectation).
  counts <- vapply(seq_len(200), function(i) {
    set.seed(10000 + i)
    o <- host.reproduce(pool, gene.df = in_file$gene, fitness.advantage = 0, cell = "haploid")
    sum(grepl("^2", o$familyTree))
  }, numeric(1))
  expect_true(mean(counts) < nrow(pool) / 2)
})

## ==========================================================================
## tPn.x()
## ==========================================================================
test_that("tPn.x invalidates the earlier transposon when spans overlap on the same gene", {
  t1 <- mk_tpn("gG1", 2, 0, valid = TRUE, size = 10)
  t2 <- mk_tpn("gG1", 2, 1, valid = TRUE, size = 10)  # identical span, same gene, later gen
  out <- tPn.x(t1, t2)
  expect_false(as.logical(tPn.io(out)["valid"]))
})

test_that("tPn.x leaves a transposon untouched when spans do not overlap or genes differ", {
  t1 <- mk_tpn("gG1", 2, 0, size = 10)
  t2 <- mk_tpn("gG2", 2, 0, size = 10)
  out <- tPn.x(t1, t2)
  expect_equal(out, t1)
})

## ==========================================================================
## tPn.r()
## ==========================================================================
test_that("tPn.r forces the valid flag TRUE on every transposon in a vector", {
  v <- c(mk_tpn("gG1", 1, 0, valid = FALSE), mk_tpn("iG2", 2, 0, valid = FALSE))
  out <- tPn.r(v)
  expect_length(out, 2)
  parsed <- lapply(out, tPn.io)
  expect_true(all(sapply(parsed, function(p) as.logical(p["valid"]))))
})

## NOTE: tPn.r() is unchanged, so its previously-flagged fragile reliance on
## read.table()'s default blank.lines.skip=TRUE to silently drop excised
## ("") transposon entries -- which could plausibly break if ALL of a host's
## transposons are excised in the same generation -- is being left as-is
## deliberately; the test that pinned it down has been removed.

## ==========================================================================
## tPn.reloc()
## ==========================================================================
test_that("tPn.reloc shifts downstream genes' start/end by the transposon size", {
  gdf <- mk_gene_df(c("g1", "g2", "g3"), start = c(1, 100, 200), end = c(50, 150, 250))
  out <- tPn.reloc(mk_tpn("", 0, 0, size = 30), gen = 1, gene.df = gdf, tPn.prob = 0.01)
  expect_true(all(out$end >= gdf$end))
})

## NOTE: tPn.reloc() is unchanged, so its previously-flagged last-gene
## boundary issue (`min(x+1, nrow(gene.df))` collapses to `x:x` when x is
## the last row, incorrectly shifting that gene's own start and leaving
## `length` inconsistent with `end - start + 1`) is being left as-is
## deliberately; the test that pinned it down has been removed. The
## contrasting non-last-gene case below is unaffected and still holds.

test_that("tPn.reloc correctly leaves the start unshifted for a non-last gene's CDS insertion", {
  gdf <- mk_gene_df(c("g1", "g2"), start = c(1, 500), end = c(100, 600))
  before_start <- gdf$start[1]
  out <- tPn.reloc(mk_tpn("", 0, 0, size = 40), gen = 1, gene.df = gdf, tPn.prob = 0.05)
  expect_equal(out$start[1], before_start)
  expect_equal(out$end[1] - out$start[1] + 1, out$length[1])
})

## ==========================================================================
## h1.mod() / sCene.mod()
## ==========================================================================
test_that("h1.mod leaves the fixed-rate value unchanged (baseline hypothesis)", {
  set.seed(11)
  out <- h1.mod(0.05, numTpn = 3, H1 = "fixed rate", gToxic = 1)
  expect_equal(out, c(0.05, 0.05))
})

test_that("h1.mod applies the genotoxic multiplier only to the first (non-inherited) value", {
  out <- h1.mod(0.10, numTpn = 3, H1 = "fixed rate", gToxic = 0)
  expect_equal(out, c(0, 0.10))
})

test_that("h1.mod's charlesworth hypothesis divides rate by transposon count", {
  out <- h1.mod(0.20, numTpn = 4, H1 = "charlesworth model", gToxic = 1)
  expect_equal(out[1], 0.05)
})

## NOTE: h1.mod() is unchanged, so its previously-flagged unguarded division
## by numTpn (Inf when numTpn == 0 under the "charlesworth" hypothesis) is
## being left as-is deliberately; the test that pinned it down has been
## removed.

test_that("sCene.mod returns 4 values ordered (jump-inherit, copy-inherit, jump, copy)", {
  set.seed(12)
  ## sCene.mod indexes sCene[2] / sCene[4] POSITIONALLY, exactly like tPn.act's
  ## real call site does -- so we pass the full one-row scenario, unsliced.
  out <- sCene.mod(pRobs = c(0.1, 0.05), tPn.bg = "gG1!1!0!TRUE!AAAAAAA!50!0.1!0.05",
                    sCene = scenario_fixture, pAram = c(0.1, 0.1, 1), gToxic = FALSE)
  expect_length(out, 4)
})

## ==========================================================================
## tPn.get()
## ==========================================================================
test_that("tPn.get(transposon=FALSE) returns just the trailing identifier", {
  colnm <- paste(mk_tpn("gA", 1, 0), mk_tpn("iB", 2, 0), "locus_tag", sep = ";")
  d <- data.frame(x = 1); colnames(d)[1] <- colnm
  expect_equal(tPn.get(d, transposon = FALSE), "locus_tag")
})

test_that("tPn.get(transposon=TRUE) returns everything except the trailing identifier", {
  colnm <- paste(mk_tpn("gA", 1, 0), mk_tpn("iB", 2, 0), "locus_tag", sep = ";")
  d <- data.frame(x = 1); colnames(d)[1] <- colnm
  expect_equal(tPn.get(d, transposon = TRUE), paste(mk_tpn("gA", 1, 0), mk_tpn("iB", 2, 0), sep = ";"))
})

test_that("tPn.get on a colname with no accumulated transposons returns an empty string", {
  d <- data.frame(x = 1); colnames(d)[1] <- "locus_tag"
  expect_equal(tPn.get(d, transposon = TRUE), "")
})

## ==========================================================================
## tPn.act()
## ==========================================================================
test_that("tPn.act leaves gene.df untouched (net of bookkeeping) when the transposon is invalid", {
  gdf <- mk_gene_df(c("g1", "g2"), start = c(1, 100), end = c(50, 150))
  colnames(gdf)[1] <- "locus_tag"
  tpn <- mk_tpn("gg1", 5, 0, valid = FALSE)
  out <- tPn.act(tpn, equivalent = FALSE, gen = 1, gene.df = gdf,
                  scenario = scenario_fixture, pAram = c(0, 0, 1), gToxic = FALSE)
  expect_equal(tPn.get(out, transposon = TRUE), "")  # invalid transposon dropped, not carried forward
})

test_that("tPn.act at generation 0 forces a jump and forbids a copy (seeding behaviour)", {
  gdf <- mk_gene_df(c("g1", "g2"), start = c(1, 100), end = c(50, 150))
  colnames(gdf)[1] <- "locus_tag"
  tpn <- mk_tpn("gg1", 5, 0, valid = TRUE, size = 10)
  out <- tPn.act(tpn, equivalent = FALSE, gen = 0, gene.df = gdf,
                  scenario = scenario_fixture, pAram = c(0, 0, 1), gToxic = FALSE)
  ## a[1] is forced TRUE, a[2] forced FALSE at gen 0 -> exactly one relocated
  ## transposon should be recorded, none copied
  recorded <- tPn.get(out, transposon = TRUE)
  expect_equal(length(strsplit(recorded, ";")[[1]]), 1)
})

## ==========================================================================
## gene.recom()
## ==========================================================================
test_that("gene.recom returns the recipient's transposon string unchanged when neither host has one at this locus", {
  out <- gene.recom("", "", g2to1 = 1, locusTags = c("g1", "g2"))
  expect_equal(out, "")
})

test_that("gene.recom transfers the donor's transposon at the target locus", {
  donor_tpn <- mk_tpn("gg2", 1, 0)
  out <- gene.recom("", donor_tpn, g2to1 = 2, locusTags = c("g1", "g2"))
  expect_equal(out, donor_tpn)
})

test_that("gene.recom's removal now uses the same 'g'-prefixed pattern as its detection check", {
  ## RESOLVED: both grep() calls in the removal steps now match
  ## paste0("g", locusTags[g2to1]) -- the SAME pattern the presence checks
  ## use -- instead of the bare tag. Previously the bare-tag removal pattern
  ## also matched an "i<tag>" (intergenic) entry at the same locus even when
  ## the presence check only looked for a "g" (coding-region) hit. Reproduced
  ## with a recipient carrying ONLY an intergenic transposon at this locus
  ## (so the outer check finds no "g" hit) alongside one at another locus
  ## that must survive untouched.
  h1 <- paste(mk_tpn("ig2", 1, 0), mk_tpn("gg9", 1, 0), sep = ";")
  out <- gene.recom(h1, "", g2to1 = 2, locusTags = c("g1", "g2", "g9"))
  expect_equal(out, h1)
})

## ==========================================================================
## g.Recom()
## ==========================================================================
test_that("g.Recom leaves the population size and column structure unchanged", {
  ## g.Recom() indexes host strings as flat CHARACTER VECTORS via
  ## strsplit(host[i], "") with a "+1" offset for haplotype-1 gene indices --
  ## that offset only makes sense if position (nGene+1) is the literal ";"
  ## separator, i.e. host must be "XXXX;YYYY" (2*nGene + 1 characters), not
  ## a bare nGene-character string.
  set.seed(13)
  h <- ini.host(4, in_file$gene, 2)
  pool <- data.frame(
    host = paste(h, h, sep = ";"),
    transposon = rep("", 4),
    familyTree = paste(1:4, 1:4, sep = ";"),
    stringsAsFactors = FALSE
  )
  ## recomRate chosen so floor(recomRate * nrow(gene.df)) >= 1, i.e. the
  ## recombination branch is actually exercised rather than a no-op
  ## (nrow(in_file$gene) == 8 here, so 0.3 * 8 = 2.4 -> floor 2).
  out <- g.Recom(pool, gene.df = in_file$gene, recomRate = 0.3, hypothesis = "switch")
  expect_equal(dim(out), dim(pool))
  expect_equal(colnames(out), colnames(pool))
})

## NOTE: g.Recom()'s recombination-mechanism check
## (`numGenes[grep(gene.df$locus_tag[i], res.pool$transposon)] <- 0`) is
## unchanged -- still an unanchored substring match with no fixed=TRUE/
## word-boundary -- so it is being left as-is deliberately; the test that
## pinned it down has been removed. (This is a distinct spot from
## gene.recom()'s removal grep, which WAS fixed above.)

}))  # end with_reporter()

## Restore the original working directory explicitly (on.exit() at top level
## of a script has no enclosing function frame to attach to, so it is not
## relied on as the only cleanup path).
setwd(old_wd)

## ==========================================================================
## Final note
## ==========================================================================
cat("\n==== test-func.R: NOTE ====\n",
    "All tests in this file are expected to PASS against the current func.r.\n",
    "============================\n\n", sep = "")
