#!/bin/env Rscript
# author: generated by Claude (Cowork) at user's request
# script: test-simulate.R
# desc: Standalone testthat tests for simulate.r (discrete-time transposon model)
# in:  Rscript test-simulate.R      (run from the SAME directory as simulate.r/func.r)
# out: console test report (testthat "summary" reporter)
# arg: NA
# date: 20260811
#
# NOTES FOR THE USER
# -------------------
# * simulate.r is a top-level SCRIPT driven by commandArgs(), not a set of
#   functions -- it cannot be "unit tested" in the usual sense without
#   amending it (which was explicitly ruled out). This file instead runs
#   simulate.r end-to-end, unchanged, as a subprocess against tiny synthetic
#   fixtures (a real integration/smoke test), and separately checks
#   simulate.r's own source text for specific, previously-identified points.
# * This is the FOURTH revision of this suite. Per the user's explicit
#   instruction this time, the new `source("sim_summary.r")` line at the
#   very end of simulate.r is IGNORED (not stubbed, not checked -- it simply
#   isn't reached by anything this suite verifies, since it runs after the
#   .rda export this suite already checks for).
# * NOT explicitly excluded, but newly present: a `source("func_analysis.r")`
#   call right after `source("func.r")`, near the top of simulate.r, BEFORE
#   any of the logic this suite exercises. Its contents were not provided.
#   Since simulate.r sources it unconditionally with no existence guard,
#   leaving it out entirely would make the smoke test fail for a reason
#   having nothing to do with simulate.r's own logic (a missing file, not a
#   real bug). This suite creates an EMPTY placeholder file for it -- sourcing
#   an empty file is a harmless no-op in R. This is an assumption, not a
#   confirmed fact about func_analysis.r's real contents: if the real file
#   defines something actually called later in the generational loop (this
#   suite found no such call in the code it inspected, so this seems
#   unlikely, but can't be ruled out from source alone), the smoke test may
#   need the real file rather than this stub. Flagged here rather than
#   silently assumed away.
# * Schema changes this revision, confirmed directly against func.r/
#   simulate.r's own source:
#     - func.r's inParams() now reads a new external "gene fitness" CSV
#       (locus_tag,fitness) instead of the old boolean essential/advantage
#       Type rows -- this suite's input.csv/gene-fitness.csv fixtures were
#       updated to match (mirrors test-func.R's fixture exactly).
#     - simulate.r's host.reproduce() call now passes
#       `transposonEffect = host.0$transposonEffect`, and its tPn.act() call
#       now passes `equivalent = ifelse(host.0$homologousAutoRecom, ...,
#       F)` -- BOTH read off host.0, meaning template-host.csv needs two
#       MORE columns than previously confirmed. Unlike this suite's other
#       template-host.csv columns (recom, recomH1, cell, genotoxic, all
#       confirmed against an uploaded file in an earlier revision),
#       transposonEffect/homologousAutoRecom are INFERRED PURELY FROM CODE
#       USAGE this time -- no fresh template-host.csv was provided alongside
#       this revision's func.r/simulate.r. Flagged explicitly rather than
#       presented as confirmed.
#     - scenario.csv's `transposon` column can now hold MULTIPLE ";"-joined
#       uniqIDs per row (`tPn.0[which(tPn.0$uniqID %in%
#       strsplit(sCene$transposon,";")[[1]]),]`). This suite's smoke test
#       fixture now deliberately selects two transposons in one scenario row
#       to exercise that path end-to-end (see fixture section below).
# * RESOLVED this revision (previously flagged, now confirmed fixed):
#     - The progress-print throttle is back to `(gEn %% 50) == 0` -- last
#       revision had reverted it to the tautological `(gEn %% 1) == 0`;
#       that regression is gone again.
#     - The tPn-catalog build now reads
#       `tPn = data.frame(ini = strsplit(tPn.io(tPn.0), ";")[[1]], ...)`
#       instead of `tPn.io(tPn.0)` directly -- this is exactly the fix for
#       last revision's [FINDING] about tPn.io()'s data.frame branch
#       collapsing multiple rows into one string (see test-func.R for the
#       direct demonstration; this file adds a quick source-text
#       confirmation that the real call site was actually changed).
# * STILL PRESENT (unchanged, flagged again): host.0 continues to be
#   selected by raw row position (`host.0[unique(sCene$host),]`) while
#   transposon selection is by uniqID value match (and, this revision, can
#   match several). See the dedicated test below.
# * IMPORTANT DISCLOSURE: authored and hand-traced line by line against
#   simulate.r's source (and the schemas confirmed in earlier revisions
#   against the actual uploaded CSVs), but could NOT be executed in the
#   authoring sandbox (no R interpreter available there, no network access
#   to install one). Please run this suite yourself and treat the first run
#   as a shakedown -- the func_analysis.r stub and the two inferred
#   template-host.csv columns noted above are the most likely sources of a
#   first-run mismatch that would NOT indicate a real bug in simulate.r.

if (!requireNamespace("testthat", quietly = TRUE)) {
  stop("Package 'testthat' is required.\nInstall it with: install.packages('testthat')")
}
suppressPackageStartupMessages(library(testthat))

## ------------------------------------------------------------------------
## 0. Locate func.r and simulate.r without modifying them
## ------------------------------------------------------------------------
this_script_dir <- function() {
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", args, value = TRUE)
  if (length(file_arg) == 1) {
    return(dirname(normalizePath(sub("^--file=", "", file_arg[1]))))
  }
  getwd()
}

locate_file <- function(fname) {
  candidates <- unique(c(file.path(getwd(), fname), file.path(this_script_dir(), fname)))
  hit <- candidates[file.exists(candidates)]
  if (length(hit) == 0) {
    stop(sprintf(
      "Could not find '%s'.\nPlace test-simulate.R in the same directory as %s and run:\n  cd <that directory> && Rscript test-simulate.R",
      fname, fname
    ))
  }
  normalizePath(hit[1])
}

FUNC_R_PATH <- locate_file("func.r")
SIMULATE_R_PATH <- locate_file("simulate.r")
RSCRIPT_BIN <- file.path(R.home("bin"), "Rscript")

## ------------------------------------------------------------------------
## 1. Build an isolated temp project tree: code/ + raw/ + data/ (siblings),
##    exactly mirroring what func.r / simulate.r expect relative to CWD.
##    Kept deliberately tiny (population size 6, 2 generations) purely so
##    the end-to-end run finishes quickly.
## ------------------------------------------------------------------------
tmp_root <- file.path(tempdir(), paste0("simulate_r_tests_", as.integer(Sys.time())))
dir.create(file.path(tmp_root, "code"), recursive = TRUE)
dir.create(file.path(tmp_root, "raw"), recursive = TRUE)
dir.create(file.path(tmp_root, "data"), recursive = TRUE)

file.copy(FUNC_R_PATH, file.path(tmp_root, "code", "func.r"), overwrite = TRUE)
file.copy(SIMULATE_R_PATH, file.path(tmp_root, "code", "simulate.r"), overwrite = TRUE)

## -- func_analysis.r: NOT provided this revision; empty placeholder so
##    simulate.r's unconditional `source("func_analysis.r")` doesn't error
##    out on a missing file. See header disclosure above.
writeLines(
  c("# empty placeholder written by test-simulate.R -- the real func_analysis.r",
    "# was not provided; see this suite's header comment for why."),
  file.path(tmp_root, "code", "func_analysis.r")
)

## -- template-tpn.csv: schema (11 columns) unchanged this revision. Two
##    distinct transposon "types" so scenario.csv's multi-uniqID selection
##    (new this revision) is genuinely exercised end-to-end, not just
##    trivially the only row available.
writeLines(c(
  "gene,location,generation,valid,uniqID,size,jumpRate,jumpH1,copyRate,copyH1,copyDir",
  ",0,0,TRUE,TEST,50,0.1,fixed,0.1,fixed,both",
  ",0,0,TRUE,DEMO,50,0.05,evolving,0.05,charlesworth,terminus"
), file.path(tmp_root, "raw", "template-tpn.csv"))

## -- template-host.csv: recom/recomH1/cell/genotoxic confirmed in an
##    earlier revision against the uploaded file; transposonEffect and
##    homologousAutoRecom are NEW columns this revision, INFERRED from code
##    usage only (see header disclosure -- no fresh file was uploaded this
##    time). Both set FALSE for the row the smoke test selects, to keep the
##    end-to-end run fully deterministic and avoid exercising those two
##    switches' internal randomness/branches in what's meant to be a fast
##    plumbing check (they're unit-tested directly in test-func.R instead).
writeLines(c(
  "recom,recomH1,cell,genotoxic,transposonEffect,homologousAutoRecom",
  "0.1,switch,haploid,1,FALSE,FALSE",
  "0.05,switch,haploid,0,FALSE,FALSE"
), file.path(tmp_root, "raw", "template-host.csv"))

gff_lines <- c(
  "seq1\ttest\tregion\t1\t2000\t.\t.\t.\tID=seq1",
  "seq1\ttest\tgene\t101\t400\t.\t+\t.\tID=gene-1;locus_tag=geneA;product=hypothetical protein A",
  "seq1\ttest\tgene\t451\t700\t.\t+\t.\tID=gene-2;locus_tag=geneB;product=hypothetical protein B",
  "seq1\ttest\tgene\t900\t1200\t.\t-\t.\tID=gene-3;locus_tag=geneC;product=recombinase-like protein",
  "seq1\ttest\tgene\t1500\t1900\t.\t-\t.\tID=gene-4;locus_tag=geneD;product=hypothetical protein D"
)
writeLines(gff_lines, file.path(tmp_root, "data", "genome.gff"))

## -- gene-fitness.csv: NEW this revision, mirrors test-func.R's fixture
##    exactly (geneC deliberately omitted -> exercises the NA -> 0 fallback).
writeLines(c(
  "locus_tag,fitness",
  "geneA,0",
  "geneB,1",
  "geneD,2"
), file.path(tmp_root, "raw", "gene-fitness.csv"))

## "essential genes" / "genes for fitness advantage" dropped -- superseded
## by "gene fitness" above (both corresponding func.r lines are commented
## out this revision). "transposon size in bp" remains dropped from an
## earlier revision (still unused).
input_csv <- c(
  "Type,Value",
  "ref genome,genome.fasta",
  "gene fitness,../raw/gene-fitness.csv",
  "genes for recombination mechanism,geneC",
  "transposon population size per genome distribution,poisson",
  "transposon population size per genome mean,2",
  "transposon population size per genome sd,2",
  "host organism constant population size,6",
  "host genome variation,6",
  "host genetic variation,2",
  "host organism constant generation number,2",
  "percentage transposon perturbation genotoxic,1",
  "percentage chance transposon perturbation boost,10",
  "percentage amplitude transposon perturbation boost,5"
)
writeLines(input_csv, file.path(tmp_root, "raw", "input.csv"))

## seed.csv: no header, one integer seed per row (argv[3] indexes into this)
writeLines(as.character(c(101, 202, 303)), file.path(tmp_root, "raw", "seed.csv"))

## scenario.csv: header=TRUE, schema (transposon,host) unchanged this
## revision. Row 1 now selects BOTH transposons ("TEST;DEMO") to exercise
## the new multi-uniqID selection path end-to-end, and host row 2
## (recom=0.05, cell=haploid, genotoxic=0, transposonEffect=FALSE,
## homologousAutoRecom=FALSE) -- row 2 specifically (not row 1) so the
## positional host lookup is genuinely exercised.
writeLines(c(
  "transposon,host",
  "TEST;DEMO,2"
), file.path(tmp_root, "raw", "scenario.csv"))

## ------------------------------------------------------------------------
## 2. Run simulate.r as a subprocess: real end-to-end smoke test, script
##    left completely unmodified.
## ------------------------------------------------------------------------
run_simulate <- function(seed_idx = "1", scenario_idx = "1") {
  old_wd <- getwd()
  on.exit(setwd(old_wd), add = TRUE)
  setwd(file.path(tmp_root, "code"))
  out <- suppressWarnings(system2(
    RSCRIPT_BIN,
    args = c("simulate.r", "../raw/input.csv", "../raw/seed.csv", seed_idx,
             "../raw/scenario.csv", scenario_idx),
    stdout = TRUE, stderr = TRUE
  ))
  status <- attr(out, "status")
  list(status = if (is.null(status)) 0L else status, output = out)
}

## ==========================================================================
## Run everything through testthat's summary reporter (see test-func.R for
## why with_reporter() is used: it lets a failing test report without
## aborting the rest of the suite).
## ==========================================================================
invisible(with_reporter("summary", start_end_reporter = TRUE, {

test_that("simulate.r runs end-to-end on tiny fixtures (incl. a multi-transposon scenario row) and writes a well-formed .rda", {
  res <- run_simulate(seed_idx = "1", scenario_idx = "1")
  if (!identical(res$status, 0L)) {
    cat("\n---- simulate.r stdout/stderr (see below for where it failed) ----\n")
    cat(paste(res$output, collapse = "\n"), "\n")
    cat("-------------------------------------------------------------------\n")
    cat("NOTE: if this failure mentions func_analysis.r or a column named\n",
        "transposonEffect/homologousAutoRecom, see this file's header comment\n",
        "-- both are assumption-based fixtures this suite had to infer.\n", sep = "")
  }
  expect_equal(res$status, 0L)

  rda_path <- file.path(tmp_root, "data", "tPn--1_1.rda")
  expect_true(file.exists(rda_path))

  if (file.exists(rda_path)) {
    e <- new.env()
    load(rda_path, envir = e)
    expect_true(all(c("rec.host", "rec.transposon", "rec.offspring") %in% ls(e)))
    ## 2 generations requested -> rows 0..2 recorded -> 3 rows; 6 individuals -> 6 columns
    expect_equal(dim(e$rec.host), c(3, 6))
    expect_equal(dim(e$rec.transposon), c(3, 6))
    expect_equal(dim(e$rec.offspring), c(3, 6))
    ## every host should carry a ";"-joined pair of haplotype genome strings
    expect_true(all(grepl(";", as.matrix(e$rec.host)[1, ])))
  }
})

## ==========================================================================
## Static/source-text checks: simulate.r is not modularised, so these pin
## down specific, previously-identified inconsistencies directly against its
## source rather than through execution.
## ==========================================================================
simulate_src <- readLines(SIMULATE_R_PATH, warn = FALSE)
simulate_txt <- paste(simulate_src, collapse = "\n")

test_that("host.reproduce() is called with the new transposonEffect argument, not the old fitness.advantage", {
  reproduce_calls <- grep("host\\.reproduce\\(", simulate_src, value = TRUE)
  expect_equal(length(reproduce_calls), 1)
  if (length(reproduce_calls) == 1) {
    expect_true(grepl('cell\\s*=\\s*host\\.0\\$cell', reproduce_calls))
    expect_true(grepl('transposonEffect\\s*=\\s*host\\.0\\$transposonEffect', reproduce_calls))
    expect_false(grepl('fitness\\.advantage', reproduce_calls))
  }
  init_branch <- grep('host\\.0\\$cell\\s*==\\s*"haploid"', simulate_src, value = TRUE)
  expect_equal(length(init_branch), 1)
})

test_that("[RESOLVED] the progress-print throttle is back to (gEn %% 50), not the tautological (gEn %% 1)", {
  ## An earlier revision reverted this to `(gEn %% 1) == 0` (always TRUE);
  ## that regression was flagged and is gone again this revision.
  expect_true(grepl("gEn %% 50", simulate_txt, fixed = TRUE))
  expect_false(grepl("gEn %% 1)", simulate_txt, fixed = TRUE))
})

test_that("[RESOLVED] the tPn catalog build now vectorises tPn.io(tPn.0) per row via strsplit", {
  ## Confirms the actual call site changed (see test-func.R for the direct
  ## demonstration of WHY this matters): `tPn.io(tPn.0)` alone would collapse
  ## every matching transposon into one combined string; wrapping it in
  ## strsplit(...,";")[[1]] recovers one flat string per row.
  expect_true(any(grepl('tPn\\s*=\\s*data\\.frame\\(ini\\s*=\\s*strsplit\\(tPn\\.io\\(tPn\\.0\\),\\s*";"\\)\\[\\[1\\]\\]', simulate_src)))
})

test_that("[FINDING] transposon selection matches by uniqID value (now even multi-valued); host selection still matches by row position", {
  ## simulate.r resolves a scenario row into working fixtures with two
  ## different lookup strategies:
  ##   tPn.0  = tPn.0[which(tPn.0$uniqID %in% strsplit(sCene$transposon,";")[[1]]),]  -- BY VALUE (now supports several)
  ##   host.0 = host.0[unique(sCene$host),]                                           -- BY POSITION (unchanged)
  ## template-host.csv still has no id column of its own, so scenario.csv's
  ## "host" column can only ever be a bare row number. The asymmetry is now
  ## slightly wider than when this was first flagged: transposon selection
  ## just gained explicit multi-value support, while host selection is
  ## untouched. Still a "finding"/awareness check, not a pass/fail bug
  ## assertion -- positional catalogs may be an accepted convention here.
  expect_true(any(grepl('tPn\\.0\\s*=\\s*tPn\\.0\\[which\\(tPn\\.0\\$uniqID %in% strsplit\\(sCene\\$transposon,\\s*";"\\)\\[\\[1\\]\\]\\)', simulate_src)))
  expect_true(any(grepl('host\\.0\\s*=\\s*host\\.0\\[unique\\(sCene\\$host\\)', simulate_src)))
})

test_that("perturbGen: genotoxic = N yields exactly N DISTINCT reachable perturbation generations (for a large enough gEn.max)", {
  ## Formula unchanged again this revision. What actually matters
  ## behaviourally is DISTINCT generations, since simulate.r only ever
  ## checks membership (`gEn %in% perturbGen`) -- a repeated value in the
  ## vector doesn't create a second "hit".
  compute_perturbGen <- function(gEn.max, genotoxic) {
    perturbGen <- ceiling(rev(seq(1, gEn.max, gEn.max / (genotoxic + 1)))) - 1
    perturbGen[perturbGen == 0] <- gEn.max + 1
    perturbGen
  }
  for (genotoxic in c(0, 1, 2, 3, 4)) {
    gEn.max <- 100
    pg <- compute_perturbGen(gEn.max, genotoxic)
    reachable <- unique(pg[pg <= gEn.max])
    expect_equal(length(reachable), genotoxic)
  }
})

test_that("[FINDING] perturbGen's 'exactly N reachable' property breaks down when gEn.max is small relative to genotoxic", {
  ## Unchanged from an earlier revision's finding (the formula itself is
  ## untouched this revision): ceiling()'s rounding can make two or more
  ## distinct raw perturbation points collapse onto the SAME integer
  ## generation when gEn.max is small relative to genotoxic+1. Verified by
  ## hand for gEn.max = 2:
  ##   genotoxic=1 -> 1 distinct reachable (matches nominal)
  ##   genotoxic=2 -> 1 distinct reachable (short of nominal 2)
  ##   genotoxic=3 -> 1 distinct reachable (short of nominal 3)
  ##   genotoxic=4 -> 1 distinct reachable (short of nominal 4)
  ## This is why the smoke test above selects a template-host.csv row with
  ## genotoxic=0 -- to stay fully deterministic rather than quietly depend
  ## on this edge case.
  compute_perturbGen <- function(gEn.max, genotoxic) {
    perturbGen <- ceiling(rev(seq(1, gEn.max, gEn.max / (genotoxic + 1)))) - 1
    perturbGen[perturbGen == 0] <- gEn.max + 1
    perturbGen
  }
  distinct_reachable <- function(gEn.max, genotoxic) {
    pg <- compute_perturbGen(gEn.max, genotoxic)
    length(unique(pg[pg <= gEn.max]))
  }
  gEn.max <- 2
  expect_equal(distinct_reachable(gEn.max, 1), 1)
  expect_equal(distinct_reachable(gEn.max, 2), 1)  # short of 2
  expect_equal(distinct_reachable(gEn.max, 3), 1)  # short of 3
  expect_equal(distinct_reachable(gEn.max, 4), 1)  # short of 4
})

}))  # end with_reporter()

## ==========================================================================
## Final note
## ==========================================================================
cat("\n==== test-simulate.R: NOTE ====\n",
    "All tests in this file are expected to PASS -- including tests labelled\n",
    "[RESOLVED] and [FINDING], which document confirmed fixes / current\n",
    "behaviour rather than open failures. See the header comment block for:\n",
    "(1) the func_analysis.r stub assumption, (2) the two INFERRED (not\n",
    "upload-confirmed) template-host.csv columns transposonEffect and\n",
    "homologousAutoRecom -- both worth double-checking against your real\n",
    "template-host.csv on first run. The end-to-end smoke test is the one\n",
    "most likely to need a fixture tweak for exactly those two reasons.\n",
    "================================\n\n", sep = "")
